# Script to define all Schemas
import pandas as pd
import numpy as np
import datetime as dt
from dateutil.relativedelta import relativedelta as rd
from pandas_schema import Column, Schema 
from pandas_schema.validation import LeadingWhitespaceValidation, TrailingWhitespaceValidation, CanConvertValidation, MatchesPatternValidation, InRangeValidation, InListValidation, IsDtypeValidation

def input_trad_schema():
    input_trad_schema = Schema([
        Column('$RID', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]) ,
        Column('CHDRNUM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]) ,  
        Column('CNTTYPE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()])  , 
        Column('BILLFREQ', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation(), InRangeValidation(0, 13)])  , # Additionally, validate possible values
        Column('BILLCHNL', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()])  ,
    # Column('SRCEBUS', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()])  ,
        Column('AGNTNUM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()])  ,
        Column('HISSDTE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation(), IsDtypeValidation(np.datetime64)]), # Additionally, validate datatype
    # Column('BNSIND', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]), 
        Column('ZREVBNS', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('BONUSAMT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]), 
        Column('ZINTRATE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),   
    # Column('ZANNTYDT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),  
        Column('STATCODE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),    
    # Column('PSTATCODE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),  
        Column('CRTABLE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]), 
        Column('LIFE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('JLIFE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]), 
        Column('COVERAGE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('RIDER', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('CRRCD', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('PCESTRM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('RCESTRM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('BCESTRM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('SUMINS', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ORIGSUM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('ZBINSTPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('EXTR', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZDISCODE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZDISPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('ZGSTPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('AGE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('RETIREAGE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('CLTDOB', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('CLTSEX', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('SMOKING', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('JLIFE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LIFCNUM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZLIFNAME', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZMEDIC', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('OCCUP', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZJLANBCD', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZJLDOB', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('JLSEX', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZJLSMOKE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('JLIFCNUM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZJLNAME', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZJMEDIC', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZJLOCCLS', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('ZYYMMINF', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('ZBSCIND', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('ZMOVECDE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('ZMOVEDTE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('TRANCDE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZLOYBON', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('WDAMNT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZMORTCHG', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CRDEBT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('SECUITYNO', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LDTH', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LDTHPM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LDTHPS', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LTPD', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LTPDPM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LTPDPS', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LCC', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LADD', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LPDPR', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LMED', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LCAC', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LECP', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LEC', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LPSU', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LZC', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('SURRVAL', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('ANNPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNLGIND', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('ZNPDD', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('TOPUPPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ETERM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ORIGPRM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ORIGSTPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LSTPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LSTGSTPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('FLAGE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('FLSEX', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('FLSMOKING', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('BENPLN', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('DDCT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZMEDVALP', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX01', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX02', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX03', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX04', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX05', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX06', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX07', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX08', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX09', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX10', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX11', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX12', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX13', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX14', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX15', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX16', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX17', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX18', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX19', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX20', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX21', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX22', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX23', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX24', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX25', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX26', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX27', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX28', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX29', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX30', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX31', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX32', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX33', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX34', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX35', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX36', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX37', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX38', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX39', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX40', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX31', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX32', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX33', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX34', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX35', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX36', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX37', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX38', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX39', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX40', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX41', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX42', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX43', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX44', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX45', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX46', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX47', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX48', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX49', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX50', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX51', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX52', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX53', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX54', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX55', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX56', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX57', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX58', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX59', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX60', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX61', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX62', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX63', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX64', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX65', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX66', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX67', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX68', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX69', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZNOUNITX70', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT01', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT02', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT03', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT04', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT05', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT06', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT07', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT08', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT09', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT10', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT11', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT12', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT13', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT14', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT15', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT16', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT17', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT18', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT19', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT20', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT21', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT22', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT23', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT24', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT25', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT26', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT27', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT28', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT29', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT30', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT31', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT32', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT33', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT34', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT35', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT36', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT37', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT38', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT39', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT40', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT41', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT42', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT43', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT44', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT45', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT46', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT47', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT48', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT49', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT50', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT51', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT52', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT53', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT54', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT55', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT56', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT57', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT58', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT59', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT60', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT61', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT62', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT63', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT64', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT65', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT66', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT67', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT68', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT69', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCUNIT70', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX01', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX02', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX03', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX04', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX05', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX06', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX07', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX08', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX09', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX10', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX11', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX12', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX13', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX14', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX15', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX16', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX17', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX18', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX19', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX20', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX21', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX22', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX23', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX24', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX25', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX26', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX27', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX28', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX29', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX30', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX31', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX32', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX33', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX34', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX35', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX36', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX37', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX38', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX39', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX40', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX41', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX42', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX43', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX44', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX45', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX46', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX47', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX48', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX49', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX50', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX51', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX52', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX53', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX54', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX55', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX56', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX57', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX58', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX59', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX60', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX61', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX62', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX63', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX64', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX65', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX66', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX67', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX68', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX69', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('INOUNITX70', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX01', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX02', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX03', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX04', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX05', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX06', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX07', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX08', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX09', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX10', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX11', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX12', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX13', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX14', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX15', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX16', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX17', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX18', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX19', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX20', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX21', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX22', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX23', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX24', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX25', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX26', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX27', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX28', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX29', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX30', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX31', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX32', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX33', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX34', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX35', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX36', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX37', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX38', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX39', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX40', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX41', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX42', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX43', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX44', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX45', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX46', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX47', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX48', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX49', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX50', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX51', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX52', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX53', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX54', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX55', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX56', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX57', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX58', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX59', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX60', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX61', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX62', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX63', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX64', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX65', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX66', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX67', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX68', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX69', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PNOUNITX70', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('TTLBASPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('TTLGCP', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('GCPFREQ', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZEDDATE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('VARSA', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('MARIND', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PAIDUPDTE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('POLLOAN', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('APLOAN', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ACCSURBEN', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CONVDTE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CONVNO', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('FUND', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('STAFFIND', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('NBAGTCODE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('SEAGTID', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('NBAGTID', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CARDTYPEX', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('APLSTART', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('APLNEXDUE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ACCCBAMT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CBAMTDT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('PROPRCDT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('FPIND', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CRISKTRM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CPREMTRM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CLAIMI', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CISI', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('RECVI', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PREGI', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('BABYI', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('OVAI', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('LSCI', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('RLL', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('CSTATCODE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('CPSTATCODE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PHLCLAIMDT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PREMALLOC', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('UNDWIND', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ACCTOPUP', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('GABSTAT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('SNLOAN', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('DADVPREM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PAYGUAR', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('DISCIND', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('RETINCM', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('ZMTHOS', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('PCESDTE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('REPRICDT', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('TNOUNITX', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('CONSTPRD', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('FUNDSRCE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CTPPP', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('CTETUP', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('INCRATE', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LSU', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('LIC', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
    # Column('DISCTIER', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()]),
        Column('FileName', [LeadingWhitespaceValidation(), TrailingWhitespaceValidation()])
])
 

    return input_trad_schema

def input_cols_to_keep():

    input_cols = ['$RID', 'CHDRNUM', 'CNTTYPE', 'BILLFREQ', 'BILLCHNL', 'AGNTNUM', 'HISSDTE', 
                  'ZREVBNS', 'ZINTRATE', 'STATCODE', 'CRTABLE', 'LIFE', 'COVERAGE', 'RIDER', 
                  'CRRCD', 'PCESTRM', 'RCESTRM', 'SUMINS', 'ZBINSTPREM', 'EXTR', 'ZGSTPREM', 
                  'AGE', 'RETIREAGE', 'CLTDOB', 'CLTSEX', 'SMOKING', 'OCCUP', 'ZYYMMINF', 'ZBSCIND', 
                  'ZMOVECDE', 'ZMOVEDTE', 'ANNPREM', 'ZNPDD', 'FLAGE', 'FLSEX', 'FLSMOKING', 
                  'BENPLN', 'GCPFREQ', 'VARSA', 'PROPRCDT', 'LSCI', 'CSTATCODE', 'CPSTATCODE', 
                  'RETINCM', 'TNOUNITX', 'CONSTPRD', 'FUNDSRCE', 'INCRATE', 'FileName'
]
    return input_cols

def prophet_output_trad_schema():
    output_trad_schema = {
        "SPCODE" : "I",
        "POL_NUMBER" : "I",
        "AGE_AT_ENTRY" : "N",
        "SEX" : "N",
        "SMOKER_STAT" : "N",
        "ENTRY_MONTH" : "N",
        "ENTRY_YEAR" : "N",
        "POL_TERM_Y" : "N",
        "BFT_PAYBL_Y" : "N",
        "PREM_PAYBL_Y" : "N",
        "PREM_FREQ" : "I",
        "PREM_MODE" : "N",
        "ANNUAL_PREM" : "N",
        "SINGLE_PREM" : "N",
        "SUBSTD_PREM" : "N",
        "SUM_ASSURED" : "N",
        "DEATH_BEN" : "N",
        "DURATIONIF_M" : "N",
        "INIT_POLS_IF" : "N",
        "INIT_DECB_IF" : "N",
        "SN_LOAN" : "N",
        "PLAN_CODE" : "N",
        "CC_ANN_PREM" : "N",
        "CC_SUM_ASSD" : "N",
        "CC_TERM_Y" : "N",
        "GN_INTRIM_RB" : "N",
        "GN_REVBON_LY" : "N",
        "PUPINDICATOR" : "N",
        "INIT_AS_IF" : "N",
        "INIT_AS_SURD" : "N",
        "AS_CURR_MTH" : "N",
        "AS_CURR_YEAR" : "N",
        "INIT_AGC_IF" : "N",
        "AGE2_ATENTRY" : "N",
        "SEX2" : "N",
        "SMOKER2_STAT" : "N",
        "FUNDTYPE" : "N",
        "DEFER_PER_Y" : "N",
        "MORT_INT_PC" : "N",
        "OCC_CLASS" : "N",
        "NONPAR_PREM" : "N",
        "LINK_PREM" : "N",
        "RIDER_BEN_PP" : "N",
        "MAT_BEN_PP" : "N",
        "G_MAT_BEN_PP" : "N",
        "SA_IND" : "N",
        "IND_PC" : "N",
        "WAIVED_STAT" : "N",
        "CI_DURIF_M" : "N",
        "NO_LS_CLAIM" : "N",
        "CIS_I" : "N",
        "RECV_I" : "N",
        "PREG_I" : "N",
        "BABY_I" : "N",
        "OVA_I" : "N",
        "LOST_I" : "N",
        "MOM_I" : "N",
        "DEL_I" : "N",
        "ISSUE_MONTH" : "N",
        "ISSUE_YEAR" : "N",
        "MME_PREM" : "N",
        "SERIES_IND" : "N",
        "RETIREMENT_AGE" : "N",
        "YTD_COST_TB" : "N",
        "WAIV_TYPE" : "N",
        "COMM_IND" : "N",
        "COMP_BEN_SA" : "N",
        "INCSA_PCT" : "N",
        "HB_SUM_ASSD" : "N",
        "SURR_FAC_1" : "N",
        "CIC_BEN_PP" : "N",
        "ACC_SUM_ASSD" : "N",
        "CC2_SUM_ASSD" : "N",
        "LS_SUM_ASSD" : "I",
        "AMR_SA_PP" : "N",
        "ROP_MAT_PC" : "N",
        "HC_SUM_ASSD" : "N",
        "INCR_BEN" : "N",
        "YI_DTH_TPD" : "N",
        "SB_BEN" : "N",
        "ADEN_BEN" : "N",
        "ECA_BEN1" : "N",
        "ECA_BEN2" : "N",
        "SB_S_YR" : "N",
        "WAIVED_IND" : "I",
        "WAIVED_PREM" : "N",
        "WAIVED_TERM" : "N",
        "RI_CED_ACHL1" : "N",
        "RI_CED_ADTL1" : "N",
        "RI_CED_ADTL2" : "N",
        "RI_CED_ADTL3" : "N",
        "RI_CED_ADTL4" : "N",
        "RI_CED_CIC1" : "N",
        "RI_CED_CIC2" : "N",
        "RI_CED_DEATH" : "N",
        "RI_CED_COMP_BEN" : "N",
        "TREATY_ID_TREATY1" : "T255",
        "TREATY_ID_TREATY2" : "T255",
        "TREATY_ID_TREATY3" : "T255",
        "TREATY_ID_TREATY4" : "T255",
        "TREATY_ID_TREATY5" : "T255",
        "PROD_CD" : "T255",
        "BENEFIT_CODE" : "T255",
        "POL_NO_IFRS17" : "T255",
        "BASIC_ENTRY_MONTH" : "N",
        "BASIC_ENTRY_YEAR" : "N"
    }

    return output_trad_schema

def prophet_par_index_output_trad_schema():
    output_trad_schema = {
        "SPCODE" : "I",
        "POL_NUMBER" : "I",
        "AGE_AT_ENTRY" : "N",
        "SEX" : "N",
        "SMOKER_STAT" : "N",
        "ENTRY_MONTH" : "N",
        "ENTRY_YEAR" : "N",
        "POL_TERM_Y" : "N",
        "BFT_PAYBL_Y" : "N",
        "PREM_PAYBL_Y" : "N",
        "PREM_FREQ" : "I",
        "PREM_MODE" : "N",
        "ANNUAL_PREM" : "N",
        "SINGLE_PREM" : "N",
        "SUBSTD_PREM" : "N",
        "SUM_ASSURED" : "N",
        "DEATH_BEN" : "N",
        "DURATIONIF_M" : "N",
        "INIT_POLS_IF" : "N",
        "INIT_DECB_IF" : "N",
        "SN_LOAN" : "N",
        "PLAN_CODE" : "N",
        "CC_ANN_PREM" : "N",
        "CC_SUM_ASSD" : "N",
        "CC_TERM_Y" : "N",
        "GN_INTRIM_RB" : "N",
        "GN_REVBON_LY" : "N",
        "PUPINDICATOR" : "N",
        "INIT_AS_IF" : "N",
        "INIT_AS_SURD" : "N",
        "AS_CURR_MTH" : "N",
        "AS_CURR_YEAR" : "N",
        "INIT_AGC_IF" : "N",
        "AGE2_ATENTRY" : "N",
        "SEX2" : "N",
        "SMOKER2_STAT" : "N",
        "FUNDTYPE" : "N",
        "DEFER_PER_Y" : "N",
        "MORT_INT_PC" : "N",
        "OCC_CLASS" : "N",
        "NONPAR_PREM" : "N",
        "LINK_PREM" : "N",
        "RIDER_BEN_PP" : "N",
        "MAT_BEN_PP" : "N",
        "G_MAT_BEN_PP" : "N",
        "SA_IND" : "N",
        "IND_PC" : "N",
        "WAIVED_STAT" : "N",
        "CI_DURIF_M" : "N",
        "NO_LS_CLAIM" : "N",
        "CIS_I" : "N",
        "RECV_I" : "N",
        "PREG_I" : "N",
        "BABY_I" : "N",
        "OVA_I" : "N",
        "LOST_I" : "N",
        "MOM_I" : "N",
        "DEL_I" : "N",
        "ISSUE_MONTH" : "N",
        "ISSUE_YEAR" : "N",
        "MME_PREM" : "N",
        "SERIES_IND" : "N",
        "RETIREMENT_AGE" : "N",
        "YTD_COST_TB" : "N",
        "WAIV_TYPE" : "N",
        "COMM_IND" : "N",
        "COMP_BEN_SA" : "N",
        "INCSA_PCT" : "N",
        "HB_SUM_ASSD" : "N",
        "SURR_FAC_1" : "N",
        "CIC_BEN_PP" : "N",
        "ACC_SUM_ASSD" : "N",
        "CC2_SUM_ASSD" : "N",
        "LS_SUM_ASSD" : "I",
        "AMR_SA_PP" : "N",
        "ROP_MAT_PC" : "N",
        "HC_SUM_ASSD" : "N",
        "INCR_BEN" : "N",
        "YI_DTH_TPD" : "N",
        "SB_BEN" : "N",
        "ADEN_BEN" : "N",
        "ECA_BEN1" : "N",
        "ECA_BEN2" : "N",
        "SB_S_YR" : "N",
        "WAIVED_IND" : "I",
        "WAIVED_PREM" : "N",
        "WAIVED_TERM" : "N",
        "RI_CED_ACHL1" : "N",
        "RI_CED_ADTL1" : "N",
        "RI_CED_ADTL2" : "N",
        "RI_CED_ADTL3" : "N",
        "RI_CED_ADTL4" : "N",
        "RI_CED_CIC1" : "N",
        "RI_CED_CIC2" : "N",
        "RI_CED_DEATH" : "N",
        "RI_CED_COMP_BEN" : "N",
        "TREATY_ID_TREATY1" : "T255",
        "TREATY_ID_TREATY2" : "T255",
        "TREATY_ID_TREATY3" : "T255",
        "TREATY_ID_TREATY4" : "T255",
        "TREATY_ID_TREATY5" : "T255",
        "PROD_CD" : "T255",
        "BENEFIT_CODE" : "T255",
        "POL_NO_IFRS17" : "T255",
        "BASIC_ENTRY_MONTH" : "N",
        "BASIC_ENTRY_YEAR" : "N",
        "PAR_COHORT_INDEX": "I"
    }

    return output_trad_schema

def python_output_schema():

    output_trad_schema = {
        'SPCODE' : 'int',
        'POL_NUMBER' : 'str',
        'AGE_AT_ENTRY' : 'int',
        'SEX' : 'int',
        'SMOKER_STAT' : 'int',
        'ENTRY_MONTH' : 'int',
        'ENTRY_YEAR' : 'int',
        'POL_TERM_Y' : 'int',
        'BFT_PAYBL_Y' : 'int',
        'PREM_PAYBL_Y' : 'int',
        'PREM_FREQ' : 'int',
        'PREM_MODE' : 'int',
        'ANNUAL_PREM' : 'float',
        'SINGLE_PREM' : 'float',
        'SUBSTD_PREM' : 'float',
        'SUM_ASSURED' : 'float',
        'DEATH_BEN' : 'float',
        'DURATIONIF_M' : 'int',
        'INIT_POLS_IF' : 'int',
        'INIT_DECB_IF' : 'float',
        'SN_LOAN' : 'str',
        'PLAN_CODE' : 'int',
        'CC_ANN_PREM' : 'float',
        'CC_SUM_ASSD' : 'float',
        'CC_TERM_Y' : 'int',
        'GN_INTRIM_RB' : 'int',
        'GN_REVBON_LY' : 'int',
        'PUPINDICATOR' : 'int',
        'INIT_AS_IF' : 'float',
        'INIT_AS_SURD' : 'float',
        'AS_CURR_MTH' : 'int',
        'AS_CURR_YEAR' : 'int',
        'INIT_AGC_IF' : 'float',
        'AGE2_ATENTRY' : 'int',
        'SEX2' : 'int',
        'SMOKER2_STAT' : 'int',
        'FUNDTYPE' : 'int',
        'DEFER_PER_Y' : 'int',
        'MORT_INT_PC' : 'float',
        'OCC_CLASS' : 'int',
        'NONPAR_PREM' : 'float',
        'LINK_PREM' : 'float',
        'RIDER_BEN_PP' : 'float',
        'MAT_BEN_PP' : 'float',
        'G_MAT_BEN_PP' : 'float',
        'SA_IND' : 'int',
        'IND_PC' : 'int',
        'WAIVED_STAT' : 'int',
        'CI_DURIF_M' : 'int',
        'NO_LS_CLAIM' : 'int',
        'CIS_I' : 'int',
        'RECV_I' : 'int',
        'PREG_I' : 'int',
        'BABY_I' : 'int',
        'OVA_I' : 'int',
        'LOST_I' : 'int',
        'MOM_I' : 'int',
        'DEL_I' : 'int',
        'ISSUE_MONTH' : 'int',
        'ISSUE_YEAR' : 'int',
        'MME_PREM' : 'float',
        'SERIES_IND' : 'int',
        'RETIREMENT_AGE' : 'int',
        'YTD_COST_TB' : 'float',
        'WAIV_TYPE' : 'int',
        'COMM_IND' : 'int',
        'COMP_BEN_SA' : 'float',
        'INCSA_PCT' : 'float',
        'HB_SUM_ASSD' : 'float',
        'SURR_FAC_1' : 'float',
        'CIC_BEN_PP' : 'float',
        'ACC_SUM_ASSD' : 'float',
        'CC2_SUM_ASSD' : 'float',
        'LS_SUM_ASSD' : 'float',
        'AMR_SA_PP' : 'float',
        'ROP_MAT_PC' : 'float',
        'HC_SUM_ASSD' : 'float',
        'INCR_BEN' : 'float',
        'YI_DTH_TPD' : 'float',
        'SB_BEN' : 'float',
        'ADEN_BEN' : 'float',
        'ECA_BEN1' : 'float',
        'ECA_BEN2' : 'float',
        'SB_S_YR' : 'float',
        'WAIVED_IND' : 'int',
        'WAIVED_PREM' : 'float',
        'WAIVED_TERM' : 'int',
        'RI_CED_ACHL1' : 'float',
        'RI_CED_ADTL1' : 'float',
        'RI_CED_ADTL2' : 'float',
        'RI_CED_ADTL3' : 'float',
        'RI_CED_ADTL4' : 'float',
        'RI_CED_CIC1' : 'float',
        'RI_CED_CIC2' : 'float',
        'RI_CED_DEATH' : 'float',
        'TREATY_ID_TREATY1' : 'str',
        'TREATY_ID_TREATY2' : 'str',
        'TREATY_ID_TREATY3' : 'str',
        'TREATY_ID_TREATY4' : 'str',
        'TREATY_ID_TREATY5' : 'str',
        'PROD_CD' : 'str',
        'BENEFIT_CODE' : 'str',
        'POL_NO_IFRS17' : 'str',
        'BASIC_ENTRY_MONTH' : 'int',
        'BASIC_ENTRY_YEAR' : 'int'

    }

    return output_trad_schema


def python_par_index_output_schema():

    output_trad_schema = {
        'SPCODE' : 'int',
        'POL_NUMBER' : 'str',
        'AGE_AT_ENTRY' : 'int',
        'SEX' : 'int',
        'SMOKER_STAT' : 'int',
        'ENTRY_MONTH' : 'int',
        'ENTRY_YEAR' : 'int',
        'POL_TERM_Y' : 'int',
        'BFT_PAYBL_Y' : 'int',
        'PREM_PAYBL_Y' : 'int',
        'PREM_FREQ' : 'int',
        'PREM_MODE' : 'int',
        'ANNUAL_PREM' : 'float',
        'SINGLE_PREM' : 'float',
        'SUBSTD_PREM' : 'float',
        'SUM_ASSURED' : 'float',
        'DEATH_BEN' : 'float',
        'DURATIONIF_M' : 'int',
        'INIT_POLS_IF' : 'int',
        'INIT_DECB_IF' : 'float',
        'SN_LOAN' : 'str',
        'PLAN_CODE' : 'int',
        'CC_ANN_PREM' : 'float',
        'CC_SUM_ASSD' : 'float',
        'CC_TERM_Y' : 'int',
        'GN_INTRIM_RB' : 'int',
        'GN_REVBON_LY' : 'int',
        'PUPINDICATOR' : 'int',
        'INIT_AS_IF' : 'float',
        'INIT_AS_SURD' : 'float',
        'AS_CURR_MTH' : 'int',
        'AS_CURR_YEAR' : 'int',
        'INIT_AGC_IF' : 'float',
        'AGE2_ATENTRY' : 'int',
        'SEX2' : 'int',
        'SMOKER2_STAT' : 'int',
        'FUNDTYPE' : 'int',
        'DEFER_PER_Y' : 'int',
        'MORT_INT_PC' : 'float',
        'OCC_CLASS' : 'int',
        'NONPAR_PREM' : 'float',
        'LINK_PREM' : 'float',
        'RIDER_BEN_PP' : 'float',
        'MAT_BEN_PP' : 'float',
        'G_MAT_BEN_PP' : 'float',
        'SA_IND' : 'int',
        'IND_PC' : 'int',
        'WAIVED_STAT' : 'int',
        'CI_DURIF_M' : 'int',
        'NO_LS_CLAIM' : 'int',
        'CIS_I' : 'int',
        'RECV_I' : 'int',
        'PREG_I' : 'int',
        'BABY_I' : 'int',
        'OVA_I' : 'int',
        'LOST_I' : 'int',
        'MOM_I' : 'int',
        'DEL_I' : 'int',
        'ISSUE_MONTH' : 'int',
        'ISSUE_YEAR' : 'int',
        'MME_PREM' : 'float',
        'SERIES_IND' : 'int',
        'RETIREMENT_AGE' : 'int',
        'YTD_COST_TB' : 'float',
        'WAIV_TYPE' : 'int',
        'COMM_IND' : 'int',
        'COMP_BEN_SA' : 'float',
        'INCSA_PCT' : 'float',
        'HB_SUM_ASSD' : 'float',
        'SURR_FAC_1' : 'float',
        'CIC_BEN_PP' : 'float',
        'ACC_SUM_ASSD' : 'float',
        'CC2_SUM_ASSD' : 'float',
        'LS_SUM_ASSD' : 'float',
        'AMR_SA_PP' : 'float',
        'ROP_MAT_PC' : 'float',
        'HC_SUM_ASSD' : 'float',
        'INCR_BEN' : 'float',
        'YI_DTH_TPD' : 'float',
        'SB_BEN' : 'float',
        'ADEN_BEN' : 'float',
        'ECA_BEN1' : 'float',
        'ECA_BEN2' : 'float',
        'SB_S_YR' : 'float',
        'WAIVED_IND' : 'int',
        'WAIVED_PREM' : 'float',
        'WAIVED_TERM' : 'int',
        'RI_CED_ACHL1' : 'float',
        'RI_CED_ADTL1' : 'float',
        'RI_CED_ADTL2' : 'float',
        'RI_CED_ADTL3' : 'float',
        'RI_CED_ADTL4' : 'float',
        'RI_CED_CIC1' : 'float',
        'RI_CED_CIC2' : 'float',
        'RI_CED_DEATH' : 'float',
        'TREATY_ID_TREATY1' : 'str',
        'TREATY_ID_TREATY2' : 'str',
        'TREATY_ID_TREATY3' : 'str',
        'TREATY_ID_TREATY4' : 'str',
        'TREATY_ID_TREATY5' : 'str',
        'PROD_CD' : 'str',
        'BENEFIT_CODE' : 'str',
        'POL_NO_IFRS17' : 'str',
        'BASIC_ENTRY_MONTH' : 'int',
        'BASIC_ENTRY_YEAR' : 'int',
        'PAR_COHORT_INDEX' : 'int'

    }

    return output_trad_schema
